#!/bin/bash

echo "Aerospace Autonomy Platform Startup Guide"
echo "========================================"
echo ""
echo "Open 4 terminals and run:"
echo ""
echo "Terminal 1: Backend"
echo "./scripts/run_backend.sh"
echo ""
echo "Terminal 2: Frontend"
echo "./scripts/run_frontend.sh"
echo ""
echo "Terminal 3: ROS2 Telemetry"
echo "./scripts/run_ros2_telemetry.sh"
echo ""
echo "Terminal 4: PX4 SITL + Gazebo"
echo "./scripts/run_px4_sitl.sh"
echo ""
echo "Frontend: http://localhost:5173"
echo "Backend Docs: http://127.0.0.1:8000/docs"
